name: getbase
version: 0.0.2
description: GetBase Flutter Plugin to Connect With GetBase
repository: https://github.com/rohitsangwan01/get_base_flutter
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'
dependencies: 
  get: ^4.3.0
  get_storage: ^2.0.3
  connectivity: ^3.0.6
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: com.getbase.getbase
        pluginClass: GetbasePlugin
      ios: 
        pluginClass: GetbasePlugin
