name: getbase
description: GetBase Flutter Plugin to Connect With GetBase
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.0
  get_storage: ^2.0.3
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.getbase.getbase
        pluginClass: GetbasePlugin
      ios:
        pluginClass: GetbasePlugin
